### ISSUE TITLE
when you get to the end and you're typing in the confirm password, but the time suddenly changes, the error thing is wrong

### ISSUE THREAD

**Issue by angusmason** [angusmason/the-password-game-2#24]
this is what it looks like:

<img width="1552" alt="image" src="https://github.com/angusmason/the-password-game-2/assets/100268469/ea0cabee-2bed-4f6c-a545-99e9b88823fa">

**Comment by circles-png** [comment]
fixed in 09564c78c105458a81519b942fb0bcdb80b80e95
